version: '3.8'

services:
  web:
    build: .
    container_name: casa_betti_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_files:/app/media
      - static_files:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=casa_betti_bacheca.settings
    stdin_open: true
    tty: true

volumes:
  media_files:
  static_files:
