# Generated by Django 5.2.7 on 2025-10-03 12:39

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo (€)')),
                ('category', models.CharField(choices=[('furniture', 'Mobili'), ('electronics', 'Elettronica'), ('clothing', 'Abbigliamento'), ('books', 'Libri'), ('sports', 'Sport'), ('other', 'Altro')], default='other', max_length=20, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('available', 'Disponibile'), ('reserved', 'Riservato'), ('sold', 'Venduto')], default='available', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Immagine')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
            options={
                'verbose_name': 'Immagine Articolo',
                'verbose_name_plural': 'Immagini Articolo',
                'ordering': ['order'],
            },
        ),
    ]
