# Generated by Django 5.2.7 on 2025-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Anno'),
        ),
    ]
