# Generated by Django 5.2.7 on 2025-10-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('furniture', 'Mobili'), ('electronics', 'Elettronica'), ('clothing', 'Abbigliamento'), ('books', 'Libri'), ('sports', 'Sport'), ('other', 'Altro'), ('paintings', "Opere d'arte")], default='other', max_length=20, verbose_name='Categoria'),
        ),
    ]
