# Generated by Django 5.2.7 on 2025-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('furniture', 'Mobili'), ('electronics', 'Elettronica'), ('clothing', 'Abbigliamento'), ('books', 'Libri'), ('sports', 'Sport'), ('other', 'Altro'), ('paintings', 'Dipinti'), ('fancy-goods', 'Oggettistica')], default='other', max_length=20, verbose_name='Categoria'),
        ),
    ]
