# Generated by Django 5.2.7 on 2025-10-03 14:12

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_background_image', filer.fields.image.FilerImageField(blank=True, help_text="Immagine di sfondo per l'intestazione del sito. Se non impostata, verrà usato il colore marrone di default.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_header_background', to=settings.FILER_IMAGE_MODEL, verbose_name='Immagine di sfondo intestazione')),
            ],
            options={
                'verbose_name': 'Impostazioni Sito',
                'verbose_name_plural': 'Impostazioni Sito',
            },
        ),
    ]
