# Generated by Django 5.2.7 on 2025-10-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Casa Betti', help_text="Titolo visualizzato nell'intestazione del sito", max_length=100, verbose_name='Titolo del Sito'),
        ),
    ]
