# Generated by Django 5.2.7 on 2025-10-04 08:17

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_sitesettings_site_title'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_background_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Immagine di sfondo per la home page (opzionale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_home_background', to=settings.FILER_IMAGE_MODEL, verbose_name='Immagine di sfondo home'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_intro_text',
            field=models.TextField(default="Scopri la nostra collezione di articoli unici e speciali. Mobili d'epoca, oggettistica, dipinti e molto altro.", help_text='Testo di introduzione visualizzato nella home page', verbose_name='Testo introduttivo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_welcome_title',
            field=models.CharField(default='Benvenuto nella Collezione Casa Betti', help_text='Titolo principale visualizzato nella home page', max_length=200, verbose_name='Titolo di benvenuto'),
        ),
    ]
